name: Deploy to Firebase production on merge into Main
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile && yarn build
      - run: |
          cd functions
          npm ci
      - name: Enter staging environment
        uses: w9jds/firebase-action@v13.4.0
        with:
          args: use production
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
      - name: Deploy Firebase Functions and Hosting
        uses: w9jds/firebase-action@v13.4.0
        with:
          args: deploy --only hosting:sandwich-orders,functions
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
